# Generated by Django 2.0.7 on 2022-04-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('Class_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('Class_name', models.CharField(max_length=30)),
                ('Class_instructor', models.CharField(max_length=30)),
                ('Class_capacity', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_name', models.CharField(max_length=30)),
                ('Client_pass', models.CharField(max_length=30)),
                ('Client_email', models.EmailField(max_length=60)),
                ('Client_phone', models.IntegerField(default=0)),
                ('Client_address', models.CharField(max_length=255)),
                ('Client_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('Client_age', models.IntegerField()),
            ],
        ),
    ]
