# Generated by Django 2.0.7 on 2022-04-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0002_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='client',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
