# Generated by Django 2.0.7 on 2022-04-22 13:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0003_auto_20220422_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.DateField(default=datetime.date(2022, 4, 22))),
                ('expired', models.DateField()),
                ('membershipType', models.CharField(choices=[('B', 'Basic'), ('S', 'Standard'), ('P', 'Premium')], default='S', max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymApp.Client')),
            ],
        ),
    ]
