# Generated by Django 2.0.7 on 2022-04-24 22:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0004_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_id', models.CharField(max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymApp.Client')),
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='initial',
            field=models.DateField(default=datetime.date(2022, 4, 25)),
        ),
    ]
