# Generated by Django 2.0.7 on 2022-04-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0005_auto_20220425_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Class_id',
            new_name='class_id',
        ),
    ]
