# Generated by Django 2.0.7 on 2022-04-27 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0007_auto_20220425_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idofapp', models.CharField(default=0, max_length=255)),
                ('name', models.CharField(default=0, max_length=255)),
                ('email', models.CharField(default=0, max_length=255)),
                ('country', models.CharField(default=0, max_length=255)),
                ('currentstate', models.CharField(default=0, max_length=255)),
                ('phonenumber', models.IntegerField(default=0)),
                ('submition_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('selectedjobid', models.CharField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idofjob', models.CharField(default=0, max_length=255)),
                ('position', models.CharField(default=0, max_length=255)),
                ('location', models.CharField(default=0, max_length=255)),
                ('salary', models.CharField(default=0, max_length=255)),
                ('jobschedule', models.CharField(default=0, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='initial',
            field=models.DateField(default=datetime.date(2022, 4, 27)),
        ),
    ]
