# Generated by Django 2.0.7 on 2022-04-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0009_auto_20220427_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membershipType',
            field=models.CharField(choices=[('B', 'Basic'), ('S', 'Standard'), ('P', 'Premium')], default='S', max_length=1),
        ),
    ]
